[package]
name = "bjw-db-derive"
version = "0.1.0"
authors = ["David Schatz"]
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
darling = "0.20.11"
